[project]
name = "michi-api"
version = "0.1.0"
description = "Backend API for Michi"
authors = [
    {name = "Julia Araujo",email = "juliagabrielly.m.araujo@gmail.com"},
]
dependencies = ["fastapi>=0.141.1", "uvicorn[standard]>=0.52.1", "sqlalchemy[asyncio]>=2.0.52", "asyncpg>=0.31.0", "alembic>=1.19.1", "pydantic-settings>=2.15.0", "psycopg2-binary>=2.9.12"]
requires-python = "==3.12.*"
readme = "README.md"


[tool.pdm]
distribution = false


[tool.pdm.scripts]

start = "docker compose up --build"
test = "pytest"
check = "ruff check ."
format = "ruff format ."
make_migration = "docker compose exec api pdm run alembic revision --autogenerate -m"
migrate = "docker compose exec api pdm run alembic upgrade head"
rollback = "docker compose exec api pdm run alembic downgrade -1"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
    "pytest>=9.1.1",
    "mypy>=2.3.0",
]
